version: "3.8"

services:
  model-api:
    container_name: model-api
    build:
      context: ./model
    ports:
      - "8000:8000"
    env_file:
      - ./model/.env
    volumes:
      - ./model:/app
    restart: unless-stopped
