version: "3.8"

services:
  kafka-producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKERS=13.228.128.157:9092
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - kafka-network

  kafka-consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKERS=13.228.128.157:9092
      - API_ENDPOINT=http://54.251.172.36:8000
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - kafka-network
    ports:
      - "8080:8080"

  kafka-debugger:
    build:
      context: ./producer
      dockerfile: Dockerfile
    command: ["python", "debug_kafka.py"]
    environment:
      - KAFKA_BROKERS=13.228.128.157:9092
      - API_ENDPOINT=http://54.251.172.36:8000
    networks:
      - kafka-network
    profiles:
      - debug

networks:
  kafka-network:
    driver: bridge
